# 預處理資料與標準化

## 預處理資料

- 建立模型的第一步就是**確認資料**。
- 確認完訓練資料，再將資料送入模型前，下一個步驟需先進行**預處理**。
- **預處理**是實務上**最花時間**，且**最重要**的步驟程序，否則「Garbage in，Garbage out」，因此需多加與耐心學習。
- 本次練習一樣使用「鐵達尼號資料集」，因為此資料集有許多種**多種資料型態**的欄位，非常適合來講解資料的預處理。

## 實作練習：鐵達尼號資料集

| 欄位名稱 | 代表意思 | 說明 |
|---|---|---|
| survival | 生還 | 0：死亡；1：存活 |
| pclass | 艙等 | 1：一等艙／2：二等艙／3：三等艙 |
| sex | 性別 | male：男性／female：女性 |
| age | 年齡 | |
| sibsp | 手足與配偶數 | 同乘的兄弟姊妹與配偶數 |
| parch | 父母與子女數 | 同乘的父母與子女數 |
| fare | 票價 | |
| embarked | 乘船港代碼 | C：Cherbourg／Q：Queenstown／S：Southampton |
| class | 艙等名 | First：一等艙／Second：二等艙／Third：三等艙 |
| who | 男女兒童 | man：男性／woman：女性／child：兒童 |
| adult_male | 成人男子 | True／False |
| deck | 甲板 | 房艙號碼首字母（A到G）|
| embark_town | 乘船港 | Southampton／Cherbourg／Queenstown |
| alive | 生還與否 | yes／no |
| alone | 單身 | True／False |

### 預處理資料 — (1) 刪除多餘資料欄位

- 資料集中有些欄位名稱雖不同，但意義卻相同，因此可檢視欄位資料，並將多餘欄位進行刪除。
- 在進行數據分析與建立模型前，最好每個欄位都具有其**獨特性**，若有某幾個欄位彼此相關，即會有多餘欄位，此狀況稱為「**多元共線性**」，若將這些欄位資料送入模型，則會造成正確性下降。
- 鐵達尼號資料集中，「艙等」與「艙等名」、「乘船港代碼」與「乘船港」、「生還」與「生還與否」這 3 組資料欄位意義相同，只需保留 1 個欄位即可。

#### 保留欄位的標準

1. **具有順序關係**的欄位：因為順序可用數值表示，應優先保留數值欄位。
2. **只有兩種值**的欄位：若欄位的值只有 0、1 兩種，則優先保留該欄位。因為保留「生還與否」欄位，而後仍需轉換成 0、1 才能送入模型中。
3. 以**實作方便性和易理解**來選擇欄位：以「乘船港代碼」與「乘船港」為例，二選一皆可，但為方便將欄位做數值編碼，建議選擇欄位值較短的「乘船港代碼」欄位。

### 預處理資料 — (2) 處理缺失值

預處理資料工作在刪除多餘欄位後，接著要確認各欄位缺失值情況。而針對**不同缺失值情況**，分別有不同的處理方式：

1. 缺失值很少的欄位，可**逐列刪除**。
2. 缺失值是數值時，可用**補值**的方式。
3. 缺失值的欄位只有固定幾類，可用**虛擬碼補值**。

#### 針對鐵達尼號資料集的三種策略

1. **乘船港代碼**：資料型態是字串。缺失值很少，只有 2 筆。→ 逐列刪除
2. **年齡**：資料型態為數值（float64）。缺失值很多，有 177 筆。→ 以資料的平均值代替
3. **甲板**：資料型態為類別（category）。缺失值很多，有 688 筆。→ 利用額外的虛擬碼取代缺失值

#### 處理缺失值的程式方式

1. **逐列刪除**：刪除含有缺失值的一整列資料，使用 `dropna`（drop NA or NaN）函式
2. **以資料的平均值代替**：填入缺失值，使用 `fillna`（fill NA or NaN）函式
3. **利用額外的虛擬碼取代缺失值**：用虛擬碼「N」取代缺失值，使用 `replace` 函式

> ※ 處理「甲板」欄位缺失值不使用 fillna 函式，是因為「甲板」資料型態是 Category，而不是字串，因此不能直接填入「N」

### 預處理資料 — (3) 處理二元資料數值化

- 當欄位資料只有 2 種類別，即為**二元資料**。
- 鐵達尼號資料集中，二元資料欄位分別有「**性別**」(male / female)、「**成年男子**」(True / False)、「**單身**」(True / False)。
- 進行欄位內容**數值化轉換**，可利用資料框的 `map` 函式

```
male   → 1    ;    True  → 1
female → 0    ;    False → 0
```

### 預處理資料 — (4) 處理多元資料數值化

- **多元資料**數值化一般會採用「**One-Hot 編碼**」。主要是根據欄位值有幾種來進行編碼。
- 若將多元資料數值化，採直覺依欄位資料中各分類進行數值分配（例如 0、1、2），則將不利於模型計算。

  > 【舉例：假設要將動物欄位中「老鼠」、「長頸鹿」、「大象」這 3 個資料數值化，則將會因**思考所設定的標準不同**，而有**不同的排列順序**。若以「體重」為標準，則順序為老鼠=0、長頸鹿=1、大象=2；若以「身高」為標準，則順序為老鼠=0、大象=1、長頸鹿=2】

- 「**One-Hot 編碼**」主要是根據欄位值有幾種來進行編碼。
- 鐵達尼號資料集中，有「男女兒童」、「乘船港代碼」、「甲板」這三個欄位都有多元資料。
- 以「男女兒童」為例，其欄位有 child、man、woman 這 3 種欄位值，因此可訂出一個 3 維編碼，讓每一種欄位值只會對應到其中 1 維（其值設為 1），其他維的值則設為 0，此為 One-Hot 編碼。

#### One-Hot 編碼示意表（男女兒童）

| 男女兒童 | 男女兒童_child | 男女兒童_man | 男女兒童_woman |
|---|---|---|---|
| man | 0 | 1 | 0 |
| woman | 0 | 0 | 1 |
| woman | 0 | 0 | 1 |
| woman | 0 | 0 | 1 |
| man | 0 | 1 | 0 |
| child | 1 | 0 | 0 |
| man | 0 | 1 | 0 |

> ⚠️ 注意：「One-Hot 編碼」的維度很高時（例如有 1000 維），則資料中會出現大量的 0（即 1000 維的資料，只會有 1000 個 1，但會有 1000×999 個 0），將這樣的資料送入模型中訓練，會造成**無謂的運算成本**。

- 「One-Hot 編碼」可應用資料框的 `get_dummies` 函式。
- `get_dummies` 函式可指定要將哪個欄位進行 One-Hot 編碼，並透過 `prefix` 參數來將指定的字串新增到自動生成的 One-Hot 欄位名稱開頭。

### 預處理資料 — (5) 資料標準化

- 資料中若有離群值，或因量測單位不同而產生數值範圍差異較大，將會造成模型訓練問題。
- 解決**離群值**或**數值範圍差異大**的問題，一般有兩種方式：
  - ① **Min-max 正規化**（Normalization）：將數值範圍**縮放到 0~1** 之間。
  - ② **Z值標準化**（Standardization）：將數值範圍**轉換成常態分布**。
- 【補充說明】資料標準化對**線性迴歸**、**邏輯斯迴歸**、**支持向量機**等演算法有效用，但對於**決策樹型**演算法就沒有必要性。

#### Min-max 正規化（Normalization）

其轉換數值方式是先找出數值範圍的**最大值**和**最小值**，然後再將每個數值**依比例縮放**到 0~1 之間。

$$\hat{x} = \frac{x - x_\mathrm{min}}{x_\mathrm{max} - x_\mathrm{min}}$$

#### Z值標準化（Standardization）

主要是將資料的**平均數移動到 0** 的位置。若資料為常態分布，將資料經 Z 值標準化轉換到「**平均值為 0，標準差為 1**」的**標準常態分布**。

$$\hat{x} = \frac{x - m}{\sigma}$$

#### 如何選擇標準化方法？

- Min-max 正規化容易受離群值影響。因此：
  - 若資料中可能**含有較大離群值** → 選擇「**Z值標準化**」
  - 若資料事先**已知最大值與最小值** → 選擇「**Min-max 正規化**」

## 實作步驟

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib_inline.backend_inline

# 將 matplotlib 圖表輸出格式設為 SVG 向量圖，放大不失真，在 Jupyter Notebook 中顯示更清晰
matplotlib_inline.backend_inline.set_matplotlib_formats("svg")

# 設定 NumPy 數字顯示格式：suppress=True 關閉科學記號，precision=4 只顯示小數點後 4 位
np.set_printoptions(suppress=True, precision=4)

# 設定 Pandas DataFrame 浮點數顯示格式為小數點後 4 位，讓表格數字對齊、易讀
pd.options.display.float_format = "{:.4f}".format

# 設定 matplotlib 圖表中所有文字（標題、軸標籤、刻度等）的預設字體大小為 14pt
plt.rcParams["font.size"] = 14

# 設定 matplotlib 圖表字體為 PingFang HK（蘋方-港），確保中文字能正確顯示
plt.rcParams["font.family"] = "PingFang HK"

### 載入 Titanic 資料集並顯示

In [2]:
import seaborn as sns

df_titanic = sns.load_dataset("titanic")
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### 更改欄位名稱為中文

In [3]:
columns_t = [
    "生還",
    "艙等",
    "性別",
    "年齡",
    "手足與配偶數",
    "父母與子女數",
    "票價",
    "乘船港代碼",
    "艙等名",
    "男女兒童",
    "成人男子",
    "甲板",
    "乘船港",
    "生還與否",
    "單身",
]

df_titanic.columns = columns_t

### 了解資料的結構與大小

In [4]:
df_titanic.head()

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,乘船港代碼,艙等名,男女兒童,成人男子,甲板,乘船港,生還與否,單身
0,0,3,male,22.0000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df_titanic.shape

(891, 15)

### 刪除多餘資料欄位

In [6]:
df1 = df_titanic.drop('艙等名', axis=1)
df2 = df1.drop('乘船港', axis=1)
df3 = df2.drop('生還與否', axis=1)
df3.head()

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,乘船港代碼,男女兒童,成人男子,甲板,單身
0,0,3,male,22.0000,1,0,7.2500,S,man,True,NaN,False
1,1,1,female,38.0000,1,0,71.2833,C,woman,False,C,False
2,1,3,female,26.0000,0,0,7.9250,S,woman,False,NaN,True
3,1,1,female,35.0000,1,0,53.1000,S,woman,False,C,False
4,0,3,male,35.0000,0,0,8.0500,S,man,True,NaN,True

> 【補充說明】`axis=1` 表示刪除欄，`axis=0` 則是刪除行。

### 處理缺失值

#### 檢查缺失值

In [7]:
df3.isnull().sum()

生還          0
艙等          0
性別          0
年齡        177
手足與配偶數      0
父母與子女數      0
票價          0
乘船港代碼       2
男女兒童        0
成人男子        0
甲板        688
單身          0
dtype: int64

In [8]:
df3['甲板'].value_counts()

甲板
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

#### 1. 逐列刪除（乘船港代碼）

In [9]:
df4 = df3.dropna(subset=['乘船港代碼'])
df4

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,乘船港代碼,男女兒童,成人男子,甲板,單身
0,0,3,male,22.0000,1,0,7.2500,S,man,True,NaN,False
1,1,1,female,38.0000,1,0,71.2833,C,woman,False,C,False
2,1,3,female,26.0000,0,0,7.9250,S,woman,False,NaN,True
3,1,1,female,35.0000,1,0,53.1000,S,woman,False,C,False
4,0,3,male,35.0000,0,0,8.0500,S,man,True,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0000,0,0,13.0000,S,man,True,NaN,True
887,1,1,female,19.0000,0,0,30.0000,S,woman,False,B,True
888,0,3,female,NaN,1,2,23.4500,S,woman,False,NaN,False
889,1,1,male,26.0000,0,0,30.0000,C,man,True,C,True
890,0,3,male,32.0000,0,0,7.7500,Q,man,True,NaN,True

#### 2. 以平均值填補（年齡）

In [10]:
age_average = df4['年齡'].mean()
df5 = df4.fillna({'年齡': age_average})
df5

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,乘船港代碼,男女兒童,成人男子,甲板,單身
0,0,3,male,22.0000,1,0,7.2500,S,man,True,NaN,False
1,1,1,female,38.0000,1,0,71.2833,C,woman,False,C,False
2,1,3,female,26.0000,0,0,7.9250,S,woman,False,NaN,True
3,1,1,female,35.0000,1,0,53.1000,S,woman,False,C,False
4,0,3,male,35.0000,0,0,8.0500,S,man,True,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0000,0,0,13.0000,S,man,True,NaN,True
887,1,1,female,19.0000,0,0,30.0000,S,woman,False,B,True
888,0,3,female,29.6421,1,2,23.4500,S,woman,False,NaN,False
889,1,1,male,26.0000,0,0,30.0000,C,man,True,C,True
890,0,3,male,32.0000,0,0,7.7500,Q,man,True,NaN,True

#### 3. 以虛擬碼取代缺失值（甲板）：

In [11]:
df6 = df5.copy()
df6['甲板'] = df6['甲板'].astype(object)
df6 = df6.replace({'甲板': {np.nan: 'N'}})
df6

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,乘船港代碼,男女兒童,成人男子,甲板,單身
0,0,3,male,22.0000,1,0,7.2500,S,man,True,N,False
1,1,1,female,38.0000,1,0,71.2833,C,woman,False,C,False
2,1,3,female,26.0000,0,0,7.9250,S,woman,False,N,True
3,1,1,female,35.0000,1,0,53.1000,S,woman,False,C,False
4,0,3,male,35.0000,0,0,8.0500,S,man,True,N,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0000,0,0,13.0000,S,man,True,N,True
887,1,1,female,19.0000,0,0,30.0000,S,woman,False,B,True
888,0,3,female,29.6421,1,2,23.4500,S,woman,False,N,False
889,1,1,male,26.0000,0,0,30.0000,C,man,True,C,True
890,0,3,male,32.0000,0,0,7.7500,Q,man,True,N,True

#### 確認缺失值已處理完畢

In [12]:
df6.isnull().sum()

生還        0
艙等        0
性別        0
年齡        0
手足與配偶數    0
父母與子女數    0
票價        0
乘船港代碼     0
男女兒童      0
成人男子      0
甲板        0
單身        0
dtype: int64

In [13]:
df6.head()

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,乘船港代碼,男女兒童,成人男子,甲板,單身
0,0,3,male,22.0000,1,0,7.2500,S,man,True,N,False
1,1,1,female,38.0000,1,0,71.2833,C,woman,False,C,False
2,1,3,female,26.0000,0,0,7.9250,S,woman,False,N,True
3,1,1,female,35.0000,1,0,53.1000,S,woman,False,C,False
4,0,3,male,35.0000,0,0,8.0500,S,man,True,N,True

### 性別轉換（二元資料數值化）

In [14]:
df6['性別'].value_counts()

性別
male      577
female    312
Name: count, dtype: int64

In [15]:
mf_map = {'male': 1, 'female': 0}
df7 = df6.copy()
df7['性別'] = df7['性別'].map(mf_map)
df7.head()

   生還  艙等  性別      年齡  手足與配偶數  父母與子女數      票價 乘船港代碼   男女兒童   成人男子 甲板     單身
0   0   3   1 22.0000       1       0  7.2500     S    man   True  N  False
1   1   1   0 38.0000       1       0 71.2833     C  woman  False  C  False
2   1   3   0 26.0000       0       0  7.9250     S  woman  False  N   True
3   1   1   0 35.0000       1       0 53.1000     S  woman  False  C  False
4   0   3   1 35.0000       0       0  8.0500     S    man   True  N   True

### 實作步驟：布林值轉換（二元資料數值化）

In [16]:
df7['成人男子'].value_counts()

成人男子
True     537
False    352
Name: count, dtype: int64

In [17]:
df8 = df7.copy()
df8['成人男子'] = df8['成人男子'].map({True: 1, False: 0})
df8.head()

   生還  艙等  性別      年齡  手足與配偶數  父母與子女數      票價 乘船港代碼   男女兒童  成人男子 甲板     單身
0   0   3   1 22.0000       1       0  7.2500     S    man     1  N  False
1   1   1   0 38.0000       1       0 71.2833     C  woman     0  C  False
2   1   3   0 26.0000       0       0  7.9250     S  woman     0  N   True
3   1   1   0 35.0000       1       0 53.1000     S  woman     0  C  False
4   0   3   1 35.0000       0       0  8.0500     S    man     1  N   True

In [18]:
df9 = df8.copy()
df9['單身'] = df8['單身'].map({True: 1, False: 0})
df9.head()

   生還  艙等  性別      年齡  手足與配偶數  父母與子女數      票價 乘船港代碼   男女兒童  成人男子 甲板  單身
0   0   3   1 22.0000       1       0  7.2500     S    man     1  N   0
1   1   1   0 38.0000       1       0 71.2833     C  woman     0  C   0
2   1   3   0 26.0000       0       0  7.9250     S  woman     0  N   1
3   1   1   0 35.0000       1       0 53.1000     S  woman     0  C   0
4   0   3   1 35.0000       0       0  8.0500     S    man     1  N   1

In [25]:
df9.describe()

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,成人男子,單身
count,889.0000,889.0000,889.0000,889.0000,889.0000,889.0000,889.0000,889.0000,889.0000
mean,0.3825,2.3116,0.6490,29.6421,0.5242,0.3825,32.0967,0.6040,0.6018
std,0.4863,0.8347,0.4775,12.9683,1.1037,0.8068,49.6975,0.4893,0.4898
min,0.0000,1.0000,0.0000,0.4200,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.0000,2.0000,0.0000,22.0000,0.0000,0.0000,7.8958,0.0000,0.0000
50%,0.0000,3.0000,1.0000,29.6421,0.0000,0.0000,14.4542,1.0000,1.0000
75%,1.0000,3.0000,1.0000,35.0000,1.0000,0.0000,31.0000,1.0000,1.0000
max,1.0000,3.0000,1.0000,80.0000,8.0000,6.0000,512.3292,1.0000,1.0000

### 實作步驟：處理類別欄位（One-Hot 編碼）

#### 1. 預覽男女兒童欄位

In [19]:
df9[['男女兒童']].head(10)

    男女兒童
0    man
1  woman
2  woman
3  woman
4    man
5    man
6    man
7  child
8  woman
9  child

In [20]:
w = pd.get_dummies(df9['男女兒童'], prefix='男女兒童')
w.head(10)

   男女兒童_child  男女兒童_man  男女兒童_woman
0       False      True       False
1       False     False        True
2       False     False        True
3       False     False        True
4       False      True       False
5       False      True       False
6       False      True       False
7        True     False       False
8       False     False        True
9        True     False       False

#### 2. 定義通用 One-Hot 編碼函數

In [21]:
def enc(df: pd.DataFrame, column: str) -> pd.DataFrame:
    df_dummy = pd.get_dummies(df[column], prefix=column)
    df_drop = df.drop([column], axis=1)
    df1 = pd.concat([df_drop, df_dummy], axis=1)
    return df1

### 3. 對各類別欄位進行編碼

In [22]:
df10 = enc(df9, '男女兒童')
display(df10.head())

df11 = enc(df10, '乘船港代碼')
df12 = enc(df11, '甲板')
display(df12.head())

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,乘船港代碼,成人男子,甲板,單身,男女兒童_child,男女兒童_man,男女兒童_woman
0,0,3,1,22.0000,1,0,7.2500,S,1,N,0,False,True,False
1,1,1,0,38.0000,1,0,71.2833,C,0,C,0,False,False,True
2,1,3,0,26.0000,0,0,7.9250,S,0,N,1,False,False,True
3,1,1,0,35.0000,1,0,53.1000,S,0,C,0,False,False,True
4,0,3,1,35.0000,0,0,8.0500,S,1,N,1,False,True,False

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,成人男子,單身,男女兒童_child,...,乘船港代碼_Q,乘船港代碼_S,甲板_A,甲板_B,甲板_C,甲板_D,甲板_E,甲板_F,甲板_G,甲板_N
0,0,3,1,22.0000,1,0,7.2500,1,0,False,...,False,True,False,False,False,False,False,False,False,True
1,1,1,0,38.0000,1,0,71.2833,0,0,False,...,False,False,False,False,True,False,False,False,False,False
2,1,3,0,26.0000,0,0,7.9250,0,1,False,...,False,True,False,False,False,False,False,False,False,True
3,1,1,0,35.0000,1,0,53.1000,0,0,False,...,False,True,False,False,True,False,False,False,False,False
4,0,3,1,35.0000,0,0,8.0500,1,1,False,...,False,True,False,False,False,False,False,False,False,True

### cleaner approach

In [23]:
df12b = pd.get_dummies(df9, columns=['男女兒童', '乘船港代碼', '甲板'], prefix=['男女兒童', '乘船港代碼', '甲板'])
display(df12b.head())

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,成人男子,單身,男女兒童_child,...,乘船港代碼_Q,乘船港代碼_S,甲板_A,甲板_B,甲板_C,甲板_D,甲板_E,甲板_F,甲板_G,甲板_N
0,0,3,1,22.0000,1,0,7.2500,1,0,False,...,False,True,False,False,False,False,False,False,False,True
1,1,1,0,38.0000,1,0,71.2833,0,0,False,...,False,False,False,False,True,False,False,False,False,False
2,1,3,0,26.0000,0,0,7.9250,0,1,False,...,False,True,False,False,False,False,False,False,False,True
3,1,1,0,35.0000,1,0,53.1000,0,0,False,...,False,True,False,False,True,False,False,False,False,False
4,0,3,1,35.0000,0,0,8.0500,1,1,False,...,False,True,False,False,False,False,False,False,False,True

### 實作步驟：數據標準化

使用 `StandardScaler` 對「年齡」與「票價」欄位進行 Z 值標準化

In [24]:
from sklearn.preprocessing import StandardScaler

df13 = df12.copy()
stdsc = StandardScaler()
df13[['年齡', '票價']] = stdsc.fit_transform(df13[['年齡', '票價']])

display(df13.head())

,生還,艙等,性別,年齡,手足與配偶數,父母與子女數,票價,成人男子,單身,男女兒童_child,...,乘船港代碼_Q,乘船港代碼_S,甲板_A,甲板_B,甲板_C,甲板_D,甲板_E,甲板_F,甲板_G,甲板_N
0,0,3,1,-0.5896,1,0,-0.5002,1,0,False,...,False,True,False,False,False,False,False,False,False,True
1,1,1,0,0.6448,1,0,0.7889,0,0,False,...,False,False,False,False,True,False,False,False,False,False
2,1,3,0,-0.2810,0,0,-0.4866,0,1,False,...,False,True,False,False,False,False,False,False,False,True
3,1,1,0,0.4134,1,0,0.4229,0,0,False,...,False,True,False,False,True,False,False,False,False,False
4,0,3,1,0.4134,0,0,-0.4841,1,1,False,...,False,True,False,False,False,False,False,False,False,True

✅ 這樣就**完成了資料的預處理與清理工作**